# Reusing code script and modules

In this notebook we will cover:

**1. code snippet**

**2. import syntax**

**3. script / modules**

**4. `if __name__==__main__:`**

**5. packages** 


### 1. Code snippet

In [1]:
msg = 'Hi, welcome to Euroscipy.'

msg.split()

['Hi,', 'welcome', 'to', 'Euroscipy.']

In [2]:
for word in msg.split():
    print(word)

Hi,
welcome
to
Euroscipy.


<div class="text-success">

<b>EXERCISE</b>:

Move this script inside a file `welcome_message.py` and run it throw the command line.

</div>

In [3]:
%run '__solved__04_welcome_message.py'

Hi,
Welcome
to
Euroscipy.


## 2. import syntax

In [4]:
import numpy

numpy.random.random((2, 2))

array([[0.99823859, 0.81048765],
       [0.98465489, 0.83465008]])

In [5]:
import numpy as np

np.random.random((2, 2))

array([[0.84262354, 0.61477275],
       [0.52957579, 0.88544775]])

In [6]:
from numpy import random

random.random((2, 2))

array([[0.26598033, 0.04438911],
       [0.84902578, 0.15290139]])

In [7]:
from numpy.random import random as rnd_mat

rnd_mat((2, 2))

array([[0.57667815, 0.8959688 ],
       [0.47435605, 0.50116522]])

## 3.  Script / modules

Lets create a module `basic_operations.py` including 2 functions: `addition` and `subtraction` which add and subtract two numbers.

We can import functions from the module `basic_operations`

In [ ]:
from basic_operations import addition, substraction

In [ ]:
addition(2, 3)

In [ ]:
substraction(2, 3)

### Demo using `sys` argument

Creating a script `operators` which uses `addition` and `substraction` from `basic_operations` with the main file

In [ ]:
%run operation.py 2 3

## 4. Packages
Directory that contains several modules, modules that contain sub-modules, and etc.

A special file called `__init__.py` (which may be empty) tells Python that the directory is a Python package, from which modules can be imported.

In [11]:
import numpy as np

In [12]:
np.__file__

'/home/mrastgoo/miniconda3/envs/py_workshop/lib/python3.6/site-packages/numpy/__init__.py'

In [13]:
np.__version__

'1.15.0'

In [14]:
from numpy import random