# Reusing code script and modules

In this notebook we will cover:
* code snippet
* import syntax
* script / modules
* `if __name__==__main__:`
* packages 


### Code snippet

In [1]:
msg = 'Hi, welcome to Euroscipy.'

msg.split()

['Hi,', 'welcome', 'to', 'Euroscipy.']

In [2]:
for word in msg.split():
    print(word)

Hi,
welcome
to
Euroscipy.


<div class="text-success">

<b>EXERCISE</b>:

Move this script inside a file `welcome_message.py` and run it throw the command line.

</div>

In [24]:
run 'welcome_message.py'

Hi,
Welcome
to
Euroscipy.


## import syntax

In [3]:
import numpy

numpy.random.random((2, 2))

array([[ 0.74375128,  0.64450871],
       [ 0.17244684,  0.02288068]])

In [4]:
import numpy as np

np.random.random((2, 2))

array([[ 0.54175615,  0.91738485],
       [ 0.75774886,  0.92515434]])

In [5]:
from numpy import random

random.random((2, 2))

array([[ 0.16813354,  0.93369973],
       [ 0.85557145,  0.95085602]])

In [6]:
from numpy.random import random as rnd_mat

rnd_mat((2, 2))

array([[ 0.34884977,  0.14467685],
       [ 0.7808681 ,  0.27365402]])

## Script / modules

Lets create a module `basic_operations.py` including 2 functions: `addition` and `subtraction` which add and subtract two numbers.

We can import functions from the module `basic_operations`

In [7]:
from basic_operations import addition, substraction

In [8]:
addition(2, 3)

5

In [9]:
substraction(2, 3)

-1

### Demo using `sys` argument

Creating a script `operators` which uses `addition` and `substraction` from `basic_operations` with the main file

In [23]:
%run operation.py 2 3

2.0 + 3.0 is 5.0
2.0 - 3.0 is -1.0


## Packages
Directory that contains several modules, modules that contain sub-modules, and etc.

A special file called `__init__.py` (which may be empty) tells Python that the directory is a Python package, from which modules can be imported.

In [25]:
import numpy as np

In [26]:
np.__file__

'/home/mrastgoo/miniconda3/envs/py_workshop/lib/python3.6/site-packages/numpy/__init__.py'

In [27]:
np.__version__

'1.15.0'

In [28]:
from numpy import random